version: "3.7"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: svq-mailhog
      ports:
        - "8001:8025"

    redis:
      image: redis:alpine
      container_name: svq-redis

    mysql:
      image: mysql:8.0
      container_name: svq-mysql
      working_dir: /application
      volumes:
        - ../:/application
        - ./svqdocker/mysql/root_pass.sql:/docker-entrypoint-initdb.d/root_pass.sql
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: svq-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./svqdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: svqdocker/php-fpm
      container_name: svq-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./svqdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: svq-phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      volumes:
        - ./svqdocker/uploads/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      ports:
        - "8080:80"
